name: ittisal2 # Detta 칛r namnet p친 ditt NYA projekt.
description: Minimal Flutter-app f칬r samtal och chatt
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Se till att detta matchar ditt Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # Korrigerad indragning och borttagen dubblett
  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  # Jitsi Meet
  jitsi_meet_flutter_sdk: ^11.3.0 # Anv칛nd den senaste stabila versionen

  # 游댒 Pushnotiser + ljud
  audioplayers: ^6.0.0 # Beh친lls som den var

  # 游 Lokal lagring
  shared_preferences: ^2.2.3 # Beh친lls som den var

  # 游꿘 WebRTC f칬r samtal
  flutter_webrtc: ^0.14.2 # Beh친lls p친 denna version, b칬r nu vara kompatibel med uppdaterad Firebase

  # 游 Beh칬righetshantering
  permission_handler: ^11.3.1 # Kompatibel med Dart SDK 3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Kompatibel med 칛ldre Dart SDK i GitHub Actions

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/ringtone.mp3
